### ISSUE TITLE
machine-config-operator doesn't work on single node cluster

### ISSUE THREAD

**Issue by stafwag** [cgruver/okd4-single-node-cluster#10]
Thanks for your nice tutorial!

The machine-config-operator doesn't seem to work on a single node cluster.
Do you know if there is a settings available to let the machine-config-operator work on a single node cluster?

**Comment by dmi3mis** [comment]
Hi!
Here is explanation in MCO docs about your problem.

https://github.com/openshift/machine-config-operator/blob/master/docs/SingleNodeOpenShift.md

When MCO is changing configuration of Red Hat CoreOS, machine-config-daemon need to apply this new configuration.
But machine-config-controller does not issue the command to change, cause there is a condition exist in machine-config-pool "no more than one missing master". I talked with developers, and they says this problem is fixed already in OpenShift 4.8 version.

dmi3mis.

**Comment by stafwag** [comment]
Thanks for the update!

I'll test it with ODK / OpenShift 4.8 when it becomes available...
